version: "3"

services:
    app:
        environment:
            - "BACKEND_ADDRESS=$BACKEND_ADDRESS"
        build:
            context: ../app
            dockerfile: Dockerfile
        networks:
            - cyberdyne
        working_dir: /app
        volumes:
            - ../app:/app
        ports:
            - "8080:8080"

    backend:
        environment:
            - "DB_ADDRESS=$DB_ADDRESS"
            - "DB_USER=$POSTGRES_USER"
            - "DB_PASSWORD=$POSTGRES_PASSWORD"
            - "DB_NAME=$POSTGRES_DB"
        build:
            context: ../backend
            dockerfile: Dockerfile
        networks:
            - cyberdyne
        working_dir: /go/src/backend
        volumes:
            - ../backend:/go/src/backend
        ports:
            - "6868:6868"

    database:
        environment:
            - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
            - "POSTGRES_USER=$POSTGRES_USER"
            - "POSTGRES_DB=$POSTGRES_DB"
        build:
            context: ../database
            dockerfile: Dockerfile
        networks:
            - cyberdyne

networks:
    cyberdyne:
        driver: bridge
